/**
 * @file 錯誤解法動物園的突變清單（見 ./run.mjs）。
 *
 * 每一項：
 * - name：突變的名稱
 * - file、find、replace：在哪個檔案把哪一段程式（必須恰好出現一次）換成什麼
 * - why：它模擬的錯誤，以及預期由哪個測試殺掉
 *
 * 刻意不收的突變：
 * - 相對上限（最佳 ＋ lemmaSpread）不把查詢本身排除：只在詞庫剛好含有查詢、而且它比真正的最佳還便宜時才會錯，
 *   隨機測試幾乎碰不到；由 finish 與 SpreadCutoff.eligible 共用同一個條件的程式審查守著。
 * - 普通搜尋（沒有交界）編譯時略過構詞音變的 continue 拿掉：admissible 在沒有交界的位置本來就不收構詞音變，
 *   只是變慢，是等價突變；junction.test.js「構詞音變只在詞素交界適用」守著結果。
 * - 確定同根不扣掉自己這一支（_dictionaryRelations 的 !down.has(k)、!up.has(k)）：自己的下層經上層繞回來，
 *   層數是往上 u ＋ u ＋ 原本的層數，一定比直接往下深，put 取最淺的一種，結果不變，是等價突變；留著只為寫明意圖。
 * - 實驗室元件（app/）的突變：動物園只跑 node 端的測試；實驗室與搜尋的一致性由 app 端的 lab-state 測試守著。
 */

export const MUTANTS = [
  {
    name: '詞素交界可以在空白旁（遮罩拿掉）',
    file: 'src/fuzzy/dp.js',
    find: 'for (let i = 0; i <= n; i++) if ((i > 0 && this.isBoundary(x[i - 1])) || (i < n && this.isBoundary(x[i]))) junctionMask[i] = 1',
    replace: 'void junctionMask',
    why: '多詞查詢會把 mu daux 分析成 mu- ＋ daux；詞綴各層的性質測試與隨機仲裁（查詢含空白）',
  },
  {
    name: '有位置限制的規則可以跨越交界',
    file: 'src/fuzzy/dp.js',
    find: '  if (start === EDGE_CROSS) return false\n',
    replace: '\n',
    why: '詞尾規則的 target 從前一段開始；ref-joint 的逐一比對與隨機仲裁',
  },
  {
    name: '交界上仍檢查 X 側的位置條件',
    file: 'src/fuzzy/dp.js',
    find: '          if (xfail && !junctions) continue',
    replace: '          if (xfail) continue',
    why: "tau'alawan 的 ' 在交界上找不到 alaw；bcdp-reference 的固定案例與 ref-joint",
  },
  {
    name: '沒有指定側的構詞音變在詞中也適用',
    file: 'src/fuzzy/dp.js',
    find: '  if (flag & FLAG_JUNCTION && !(flag & (FLAG_INITIAL | FLAG_FINAL)) && start !== EDGE_JUNCTION && end !== EDGE_JUNCTION) return false\n',
    replace: '\n',
    why: '構詞搜尋的詞幹內部也套用構詞音變；ref-joint 的逐一比對',
  },
  {
    name: '交界狀態合併時不取 min',
    file: 'src/fuzzy/junction.js',
    find: '    if (v < into.row[x] || (v === into.row[x] && v < Infinity && before?.(tag, into.tags.row[x]))) {',
    replace: '    if (v < Infinity) {',
    why: '後合併的詞綴鏈蓋掉較便宜的；詞綴各層合併的性質測試',
  },
  {
    name: 'CVCVC 不收韻尾',
    file: 'src/fuzzy/morphology.js',
    find: "if (pattern === 'CVCVC') while (k < n && !vowels.has(chars[k])) k++",
    replace: "if (pattern === 'CVCVC') void n",
    why: 'kudung~kudung 找不到；morphology 的模板表與 bcdp-reference 的重疊型式',
  },
  {
    name: '穩定引理差一',
    file: 'src/fuzzy/morphology.js',
    find: 'if (whole === red) for (let l = stable; l <= rest.length; l++) out.push(l)',
    replace: 'if (whole === red) for (let l = stable + 1; l <= rest.length; l++) out.push(l)',
    why: '詞幹剛好等於模板長度時漏掉；reduplicantStems 的性質測試',
  },
  {
    name: 'CVG 不檢查第一個元音是不是滑音（ziu 同時是 CGV 與 CVG）',
    file: 'src/fuzzy/morphology.js',
    find: "const ok = pattern === 'CGV' ? onglide : !onglide && glides.has(chars[v1 + 1])",
    replace: "const ok = pattern === 'CGV' ? onglide : glides.has(chars[v1 + 1])",
    why: 'CVG(ziux) 應該不適用；morphology.test.js 的模板表與參考實作的隨機仲裁',
  },
  {
    name: 'CGV、CVG 的元音核可以超過兩個元音',
    file: 'src/fuzzy/morphology.js',
    find: 'if (k - v1 !== 2 || chars[v1] === chars[v1 + 1]) return null',
    replace: 'if (k - v1 < 2 || chars[v1] === chars[v1 + 1]) return null',
    why: '穩定引理與 reduplicantStems 的逐一檢查（uia… 開頭的詞幹）、參考實作的隨機仲裁',
  },
  {
    name: '剪枝過度（上限少 0.05）',
    file: 'src/fuzzy/fuzzy-index.js',
    find: 'const pruned = endEdge > firstEdge && lowerBound > bound + EPSILON',
    replace: 'const pruned = endEdge > firstEdge && lowerBound > bound - 0.05',
    why: '剛好在上限內的詞被剪掉；邊界條件與詞圖搜尋的暴力比對',
  },
  {
    name: '多通道漏掉第 0 個通道',
    file: 'src/fuzzy/fuzzy-index.js',
    find: 'if (!pruned) next[nextCount++] = c',
    replace: 'if (!pruned && c > 0) next[nextCount++] = c',
    why: '普通模糊搜尋（通道 0）只剩根節點；多通道性質測試與幾乎所有搜尋測試',
  },
  {
    name: '詞尾規則在詞尾前一格也適用',
    file: 'src/fuzzy/dp.js',
    find: "(rule.position === 'final' && !(i === n || this.isBoundary(x[i]))))",
    replace: "(rule.position === 'final' && !(i >= n - 1 || this.isBoundary(x[i]))))",
    why: '詞中的 l 被當成詞尾；refDistance 的逐一比對',
  },
  {
    name: 'align 同分時取後回報的候選',
    file: 'src/fuzzy/distance.js',
    find: 'c === cost[at] && p < priority[at]',
    replace: 'c === cost[at] && p <= priority[at]',
    why: '對齊與 explain 不同；explain 測試的 align 比對',
  },
  {
    name: '相對上限的起點當成處處可以在詞尾結束',
    file: 'src/fuzzy/morph-search.js',
    find: 'prefixed + (y === n ? 0 : S.row[y])',
    replace: 'prefixed',
    why: '起點比真正的最佳還低，剪掉最佳 ＋ spread 之內的詞；morph-search「相對上限」的性質測試',
  },
  {
    name: '耦合位能不取之後的最小值',
    file: 'src/fuzzy/fuzzy-index.js',
    find: '        for (let x = n - 1; x >= 0; x--) if (e[x + 1] < e[x]) e[x] = e[x + 1]',
    replace: '        void e',
    why: '位能高估（之後的位置結束更便宜），剪掉上限內的詞；隨機仲裁',
  },
  {
    name: '前綴式環綴的通道可以不接後綴就結束',
    file: 'src/fuzzy/morph-search.js',
    find: 'to: { row: end.row, pending: end.pending, word: null } } })',
    replace: 'to: { row: end.row, pending: end.pending, word } } })',
    why: 'ta-kita 被當成 ta-…-aw；bcdp-reference 的固定案例「環綴一定要接它的後綴」與隨機仲裁（環綴）',
  },
  {
    name: '中綴、重疊式環綴的變體可以不接後綴就結束',
    file: 'src/fuzzy/morph-search.js',
    find: '        if (member.suffix === null && v.ends(m)) vWord[m] = Math.min(vWord[m], member.cost)',
    replace: '        if (v.ends(m)) vWord[m] = Math.min(vWord[m], member.cost)',
    why: 'binaket 被當成 <in>…-an；bcdp-reference 的固定案例「環綴一定要接它的後綴」與隨機仲裁（環綴）',
  },
  {
    name: '環綴的成本沒有算進起點',
    file: 'src/fuzzy/morph-search.js',
    find: 'mergeInto((group.start ??= emptyJunction(n)), Pc, c.cost, c, byRank)',
    replace: 'mergeInto((group.start ??= emptyJunction(n)), Pc, 0, c, byRank)',
    why: '環綴免費；bcdp-reference 的隨機仲裁與 search/morphology 的環綴測試',
  },
  {
    name: '環綴的兩側只從詞首（詞尾）出發',
    file: 'src/fuzzy/morph-search.js',
    find: '    if (isReachable(after)) origins.push({ from: after, origin: 1 })',
    replace: '    void after',
    why: '外面再加前綴的環綴（mu-bin…an）找不到；bcdp-reference 的隨機仲裁與 search/morphology 的環綴測試',
  },
  {
    name: '交界狀態合併跨界表時不取 min',
    file: 'src/fuzzy/junction.js',
    find: '      if (v < target.row[x] || (v === target.row[x] && v < Infinity && before?.(tag, tags[x]))) {',
    replace: '      if (v < Infinity) {',
    why: '跨界規則由後合併的鏈蓋掉較便宜的（例如後綴相同的環綴共用起點）；詞綴各層合併的性質測試與隨機仲裁',
  },
  {
    name: '重複的查詢詞不累加走訪統計',
    file: 'src/search/engine.js',
    find: 'response.stats.visitedNodes += prev.visited',
    replace: 'void prev.visited',
    why: '回應的統計與逐次計算不同；engine 測試「重複的查詢詞只算一次，統計照樣累加」',
  },
  {
    name: '構詞命中遇到同一個詞的模糊命中一律捨棄（v0.2.0 起的原始寫法）',
    file: 'src/search/scoring.js',
    find: '  if (a >= b - EPSILON) return keep(prev, m)\n  return keep(m, prev)',
    replace: '  return keep(prev, m)',
    why: '查 parazem 時 razem 只剩模糊命中 1.2；morphology 測試「同一個詞有多種命中方式」、scoring 測試',
  },
  {
    name: '詞條家族的名次取樹根的分數，而不是家族中最好的命中',
    file: 'src/search/family.js',
    find: '    const best = all.reduce((a, b) => (compareHits(b, a) < 0 ? b : a))',
    replace: '    const best = root.hit ?? all[0]',
    why: '子項目完全相同時家族不會往上排；family 測試「家族的名次取最好的命中」',
  },
  {
    name: '構詞文法：中綴插在前綴首輔音之後的位置差一',
    file: 'src/fuzzy/grammar.js',
    find: '      if (h < chars.length) L = [...chars.slice(0, h), s.form, ...chars.slice(h)].join(\'\')',
    replace: '      if (h < chars.length) L = [...chars.slice(0, h + 1), s.form, ...chars.slice(h + 1)].join(\'\')',
    why: 'mu ＋ <in> 展開成 muin 而不是 minu；grammar.test 的展開結果與引理',
  },
  {
    name: '構詞文法：沒有元音的前綴插入中綴時直接接成字串（不交給詞根）',
    file: 'src/fuzzy/grammar.js',
    find: '      if (h < chars.length) L = [...chars.slice(0, h), s.form, ...chars.slice(h)].join(\'\')\n      else if (op)',
    replace: '      if (true) L = [...chars.slice(0, h), s.form, ...chars.slice(h)].join(\'\')\n      else if (op)',
    why: 'm<a>- 對輔音開頭的詞根也成了 ma-（mabaket 被說成 m<a>-）；grammar.test 的引理與固定案例',
  },
  {
    name: '構詞文法：組合規則的詞素順序顛倒',
    file: 'src/fuzzy/grammar.js',
    find: '      for (const form of formsOf(members[k])) walk(k + 1, [...parts, partOf(members[k], form)])',
    replace: '      for (const form of formsOf(members[k])) walk(k + 1, [partOf(members[k], form), ...parts])',
    why: '推導順序反了（mu ＋ <in> 變成 <in> ＋ mu）；grammar.test 的展開結果',
  },
  {
    name: '包覆單位的外側前綴沒有算進詞幹的起點（起點取自自由的前綴鏈）',
    file: 'src/fuzzy/morph-search.js',
    find: '        const Pc = circP.get(outer)',
    replace: '        const Pc = P',
    why: 'm<a>- 的 m 不用付對齊的成本；bcdp-reference 的窮舉比對（wrap:outer）',
  },
  {
    name: '要求詞幹元音開頭的環綴沒有限制詞幹（併進通道時，所有詞都由合併後的起點出發）',
    file: 'src/fuzzy/morph-search.js',
    find: '      options.initialFrom = { initials: vowelSet, from: start }',
    replace: '      options.from = start',
    why: 'mabaket 被說成 m<a>- ＋ baket；grammar.test 的固定案例與 bcdp-reference 的窮舉比對',
  },
  {
    name: '說明時元音開頭的詞仍由原本的起點追溯（沒有用合併後的起點）',
    file: 'src/fuzzy/morph-search.js',
    find: '    const start = v.alt && vowelSet.has(Array.from(result.term)[0]) ? v.alt.start : /** @type {Level | undefined} */ (options.from)',
    replace: '    const start = /** @type {Level | undefined} */ (options.from)',
    why: '由元音開頭環綴得到的命中說明不出環綴（或追溯出錯）；grammar.test 的 mausay 與 bcdp-reference 的固定案例',
  },
  {
    name: '元音開頭環綴併進前綴鏈的起點時，同分改成環綴優先（不看步驟數與規格順序）',
    file: 'src/fuzzy/morph-search.js',
    find: '  if (current > 1) return true\n',
    replace: '  return true\n',
    why: 'mausa 被說成 m<a>-（自由詞素 ma- 應該優先）；grammar.test 的固定案例',
  },
  {
    name: 'initialFrom：以 initials 開頭的詞沒有換上另一個起點的跨界表',
    file: 'src/fuzzy/fuzzy-index.js',
    find: '              const cross = alt ? a.cross : base.cross',
    replace: '              const cross = base.cross',
    why: '跨越交界的規則在另一個起點上失效；junction.test 的 initialFrom 性質測試',
  },
  {
    name: 'initialFrom：根節點的每條邊用錯了哪一套起點的下界剪枝',
    file: 'src/fuzzy/fuzzy-index.js',
    find: '              if ((alt ? a.lowerBound : base.lowerBound) > bound + EPSILON) continue',
    replace: '              if ((alt ? base.lowerBound : a.lowerBound) > bound + EPSILON) continue',
    why: '該走的子樹被剪掉；junction.test 的 initialFrom 性質測試',
  },
  {
    name: '同分時的說明選規格中較後的',
    file: 'src/fuzzy/morph-search.js',
    find: '  for (let k = 0; k < Math.min(x.length, y.length); k++) if (x[k] !== y[k]) return x[k] - y[k]',
    replace: '  for (let k = 0; k < Math.min(x.length, y.length); k++) if (x[k] !== y[k]) return y[k] - x[k]',
    why: 'mausa、mausay 被說成 ma-（靜態）；grammar.test 的固定案例',
  },
  {
    name: '自動派生圖收下所有詞根，不只最好的',
    file: 'src/search/derivations.js',
    find: '    if (hit.distance > hits[0].distance + EPSILON) continue',
    replace: '      void hits',
    why: 'pausunguday 直接連到 sungut（雜訊多）；derivations 測試「最好詞根是 pusungut，不是 sungut」',
  },
  {
    name: '自動派生圖依詞編號（字典序）鬆弛，不依詞長',
    file: 'src/search/derivations.js',
    find: '.sort((a, b) => this._len(a) - this._len(b) || a - b)',
    replace: '.sort((a, b) => a - b)',
    why: '字典序不是拓撲順序：pausunguday 在 pusungut 之前處理，走不到；derivations 測試「查 sungut 找到 pausunguday」',
  },
  {
    name: '自動派生圖只限制每一條邊，不限制整條路徑',
    file: 'src/search/derivations.js',
    find: '        if (path > maxPath + EPSILON) continue',
    replace: '        void path',
    why: '兩條各在上限內的邊相加超過上限；derivations 測試「路徑成本不超過上限」',
  },
  {
    name: '寬鬆時仍只用方言變體當自動派生的起點',
    file: 'src/search/engine.js',
    find: '    return level.derivedFromAll || (m.distance',
    replace: '    return false || (m.distance',
    why: '查 sugut 找不到 pausunguday；derivations 測試「寬鬆：查詢的相近寫法也當起點」',
  },
  {
    name: '開頭相符、包含的詞能自動派生時仍保留原本的命中',
    file: 'src/search/scoring.js',
    find: '  if (PARTIAL.has(prev.matchType)) return keep(m, prev, { score: Math.min(a, b) })',
    replace: '  if (PARTIAL.has(prev.matchType)) return keep(prev, m)',
    why: '開頭相符的 sungutan 沒有派生的說明；derivations 測試「開頭相符又能自動派生的詞」、scoring 測試',
  },
  {
    name: '辭典派生詞不加層數的差距',
    file: 'src/search/scoring.js',
    find: '  return Math.round((score + depth * DERIVATIVE_PENALTY) * 1e9) / 1e9',
    replace: '  return score',
    why: '派生詞與詞本身同分；scoring 測試、derivations 測試「含 mukusa 的例句分數是 usa 的分數加一層」',
  },
  {
    name: '例句的辭典派生詞也從寫法相近的詞條展開',
    file: 'src/search/engine.js',
    find: "        if (t.matchType !== 'fuzzy' || t.distance > 0) continue",
    replace: "        if (t.matchType !== 'fuzzy') continue",
    why: '查 sungut 時 zenget 的派生詞 kizenget 排到 pausunguday 之前；derivations 測試「只從寫法與查詢相同的詞條展開」',
  },
  {
    name: '虛擬詞根不加詞庫外詞根的代價（只要比詞庫中的詞根便宜就建）',
    file: 'src/search/derivations.js',
    find: '  for (const list of results) for (const r of list) score.set(r.term, Math.min(score.get(r.term) ?? Infinity, r.distance + virtualRootCost(r.term, spec)))',
    replace: '  for (const list of results) for (const r of list) score.set(r.term, Math.min(score.get(r.term) ?? Infinity, r.distance))',
    why: 'dakudan 另建虛擬詞根 dakud（詞庫已有 dakut，只差構詞音變）；derivations 測試「只在詞庫解釋不了時建立」',
  },
  {
    name: '虛擬詞根的代價是固定的 0.1（少了長度懲罰，舊版的條件 1）',
    file: 'src/search/derivations.js',
    find: '  for (const list of results) for (const r of list) score.set(r.term, Math.min(score.get(r.term) ?? Infinity, r.distance + virtualRootCost(r.term, spec)))',
    replace: '  for (const list of results) for (const r of list) score.set(r.term, Math.min(score.get(r.term) ?? Infinity, r.distance + 0.1))',
    why: 'pinahazaban 另建 pinahazab（詞庫的 pina-hazap-an 只貴 0.05）、mabubuer 同時建 bubuer 與 abubuer；derivations 測試「三個原則」',
  },
  {
    name: '虛擬詞根不檢查形狀（一個音節也收）',
    file: 'src/search/derivations.js',
    find: '  const keep = (/** @type {string} */ v) => Array.from(v).length < length && index.dawg.lookup(v) === -1 && isVirtualRootShape(v, spec)',
    replace: '  const keep = (/** @type {string} */ v) => Array.from(v).length < length && index.dawg.lookup(v) === -1',
    why: 'karaw 拆出 raw，與所有 -raw 結尾的詞巧合同根；derivations 測試',
  },
  {
    name: '虛擬詞根的分析用一般的距離函式（詞綴可以有方言音變）',
    file: 'src/search/derivations.js',
    find: '  return createMorphSearch({ analyzer: /** @type {import(\'../fuzzy/morphology.js\').Analyzer} */ (text.morphology), metric: text.createAlternationMetric(), index })',
    replace: '  return createMorphSearch({ analyzer: /** @type {import(\'../fuzzy/morphology.js\').Analyzer} */ (text.morphology), metric: text.createSearchMetric(), index })',
    why: 'mobubuer（mu- 的方言寫法）也拆出 bubuer，詞根不在詞庫中還加上模糊；derivations 測試「詞綴必須原樣出現」',
  },
  {
    name: '第 2 階段不過濾「詞本身是別的詞的詞根」',
    file: 'src/search/derivations.js',
    find: '  return candidates.filter((e) => !isLexicalRoot(index, e.word, (id) => roots.has(id)))',
    replace: '  return candidates',
    why: 'samian 拆成 sa- ＋ 虛擬詞根 mian；derivations 測試「虛擬詞根的對稱」',
  },
  {
    name: '開放詞幹不在詞幹結尾還原構詞音變',
    file: 'src/fuzzy/morph-search.js',
    find: "          if (endJ < Infinity) for (const r of junctionRules) if (r.position !== 'initial' && span.endsWith(r.source)) tails.push({ tail: r.target, skip: r.source.length, cost: endJ + r.weight, kind: 'row' })",
    replace: '',
    why: '窮舉找到的 bitut（bitudun ＝ bitut ＋ -un）在開放詞幹裡沒有；bcdp-reference「字面的開放詞幹」、morphology 測試',
  },
  {
    name: '開放詞幹不在詞幹開頭還原構詞音變',
    file: 'src/fuzzy/morph-search.js',
    find: "          if (junctionStart) for (const r of junctionRules) if (r.position !== 'final' && span.startsWith(r.source)) heads.push({ head: r.target, skip: r.source.length, cost: r.weight })",
    replace: '',
    why: '詞首位置的構詞音變（a → na）在前綴之後的詞幹開頭；bcdp-reference「字面的開放詞幹」',
  },
  {
    name: '開放詞幹的起點不分元音開頭（要求元音開頭的環綴也給其他詞幹）',
    file: 'src/fuzzy/morph-search.js',
    find: '      const startOf = (i, first) => (o.initialFrom?.initials.has(first) ? o.initialFrom.from.row[i] : (base?.[i] ?? Infinity))',
    replace: '      const startOf = (i, first) => Math.min(o.initialFrom ? o.initialFrom.from.row[i] : Infinity, base?.[i] ?? Infinity)',
    why: 'ma-（m<a> 在元音開頭的詞幹上）也接在輔音開頭的詞幹前；bcdp-reference「字面的開放詞幹」',
  },
  {
    name: '自動同根：查詢本身是別的詞的詞根時也拆虛擬詞根',
    file: 'src/search/engine.js',
    find: '    if (!isLexicalRoot(this.index, self, (id) => graph.hasChildren(id))) {\n      const open',
    replace: '    if (true) {\n      const open',
    why: '查 samian 找到 mumian（samian 拆成 sa- ＋ 虛擬詞根 mian）；derivations 測試「虛擬詞根的對稱」',
  },
  {
    name: '自動同根：經過虛擬詞根不加詞庫外詞根的代價',
    file: 'src/search/engine.js',
    find: '        if (id !== undefined) virtualSeeds.push({ id, distance: roundCost(v.cost + penalty), term: v.stem, split: { cost: v.cost, steps: v.steps, penalty, lexical: false } })',
    replace: '        if (id !== undefined) virtualSeeds.push({ id, distance: roundCost(v.cost), term: v.stem, split: { cost: v.cost, steps: v.steps, penalty, lexical: false } })',
    why: '查 binubuer 時 mabubuer 的分數少了 0.18；derivations 測試的分數',
  },
  {
    name: '自動同根：詞庫詞根往下走整棵子樹（不只直接的子詞）',
    file: 'src/search/engine.js',
    find: '      .childrenOf(lexicalSeeds, { maxPath, maxSound: SIBLING_MAX_SOUND })',
    replace: '      .descendants(lexicalSeeds, maxPath)',
    why: '查 masamian 經 samian 走到孫輩 musamianan；derivations 測試「自動同根：詞根在詞庫中」',
  },
  {
    name: '自動同根：查詢拆到詞庫詞根的音變不設上限',
    file: 'src/search/engine.js',
    find: '      if (soundOf({ cost: m.distance, steps: m.analysis.steps }) > SIBLING_MAX_SOUND + EPSILON) continue',
    replace: '',
    why: '查 makétéko（三個方言音變才拆到 kitiku）也往上找到 mukitiku；derivations 測試「兩條邊都要是可靠的拆法」',
  },
  {
    name: '自動同根：詞根往下的邊不檢查音變',
    file: 'src/search/derivations.js',
    find: '        if (seedIds.has(c.word) || soundOf(analysis) > maxSound + EPSILON || cost > maxPath + EPSILON) continue',
    replace: '        if (seedIds.has(c.word) || cost > maxPath + EPSILON) continue',
    why: '音變多的巧合邊（lat → balas）也算同根；derivations 測試「同根只取詞根的直接子詞」',
  },
  {
    name: '自動同根不排在原本的命中之後',
    file: 'src/search/scoring.js',
    find: "export const siblingTier = (h) => (h.matchType === 'sibling' || /** @type {{matches?: Array<{matchType: MatchType}>}} */ (h).matches?.some((m) => m.matchType === 'sibling') ? 1 : 0)",
    replace: 'export const siblingTier = (h) => 0',
    why: '分數較好的同根詞排到原本的命中前面、擠掉它們；derivations 測試「排序」「不佔上限」',
  },
  {
    name: '自動同根取代開頭相符、包含（把原本的命中擠到最後）',
    file: 'src/search/scoring.js',
    find: "  if (m.matchType === 'sibling') return keep(prev, m)\n  if (PARTIAL.has(prev.matchType)) return keep(m, prev, { score: Math.min(a, b) })",
    replace: "  if (PARTIAL.has(prev.matchType)) return keep(m, prev, { score: Math.min(a, b) })\n  if (m.matchType === 'sibling') return keep(prev, m)",
    why: '查 maatebe 時開頭相符的 maatebeteber 變成自動同根、排到最後；scoring 測試「自動同根不取代任何命中」',
  },
  {
    name: '自動同根也佔上限',
    file: 'src/search/engine.js',
    find: '    response.entries = capped(response.entries, siblingTier)',
    replace: '    response.entries = response.entries.slice(0, limit)',
    why: 'limit 之外的同根詞消失；derivations 測試「不佔上限」',
  },
  {
    name: '自動同根：只走虛擬詞根（沒有詞庫中的詞根）',
    file: 'src/search/engine.js',
    find: '      if (id !== -1) lexicalSeeds.push({ id, distance: m.distance, term: m.term, split: { cost: m.distance, steps: m.analysis.steps, penalty: 0, lexical: true } })',
    replace: '',
    why: '查 masamian 找不到 musamian（共同的詞根 samian 在詞庫中）；derivations 測試「自動同根：詞根在詞庫中」',
  },
  {
    name: '自動同根取代分數較差的其他命中',
    file: 'src/search/scoring.js',
    find: "  if (m.matchType === 'sibling') return keep(prev, m)\n",
    replace: '',
    why: '原本的自動派生、自動拆解被自動同根蓋掉；derivations 測試「自動同根不取代其他命中」',
  },
  {
    name: '被取代的命中不留下來（排除取代它的方法時連它也消失）',
    file: 'src/search/scoring.js',
    find: '  return [m, .../** @type {T[]} */ (m.others ?? [])]',
    replace: '  return [m]',
    why: '排除自動派生後，原本開頭相符的 sungutan 也不見；derivations 測試「搜尋方法」',
  },
  {
    name: '辭典的構詞關係沒有上層（確定拆解）',
    file: 'src/search/engine.js',
    find: "    for (const [k, d] of up) put(k, 'parent', d)",
    replace: '    void up',
    why: '查 pinakita 時 kita-、pakita 不是確定拆解；family 測試',
  },
  {
    name: '記錄上的自動同根與其他命中一樣比分數',
    file: 'src/search/scoring.js',
    find: '  if (a !== b) return b\n',
    replace: '\n',
    why: '詞條的原本命中被自動同根取代；derivations 測試（replacesRecordHit）',
  },
  {
    name: '詞綴的條目也當成同根的依據',
    file: 'src/search/engine.js',
    find: '      if (this._isAffixEntry(a)) continue\n',
    replace: '\n',
    why: '<in> 條下的例子（binaket）成了 kinawas 的確定同根；derivations 測試「詞綴的條目不算同根」',
  },
  {
    name: '家族排序不看記錄原本的直接命中',
    file: 'src/search/family.js',
    find: '    const own = all.filter((h) => h.direct ?? !DICTIONARY_KINDS.has(h.kind))',
    replace: '    const own = all.filter((h) => !DICTIONARY_KINDS.has(h.kind))',
    why: '自動拆解到的 kawas- 以確定拆解呈現後不算證據，<in> 條排到 kawas- 條之前；derivations 測試',
  },
  {
    name: '另立條目對到多個同形詞目時接到第一個',
    file: 'src/search/family.js',
    find: '        if (all.length === 1) return all[0]',
    replace: '        if (all.length >= 1) return all[0]',
    why: '同形異義詞被接錯；family 測試「對不到唯一一個詞目時不連」',
  },
  // 句型搜尋（src/pattern）
  {
    name: '句型：重疊不貪婪（先停再多比）',
    file: 'src/pattern/match.js',
    find: `    if (count < node.max) {
      for (const e of ends(node.node, i)) {
        if (e > i) pushUnique(out, seen, repeatEnds(node, e, count + 1))
      }
    }
    if (count >= node.min) pushUnique(out, seen, [i])`,
    replace: `    if (count >= node.min) pushUnique(out, seen, [i])
    if (count < node.max) {
      for (const e of ends(node.node, i)) {
        if (e > i) pushUnique(out, seen, repeatEnds(node, e, count + 1))
      }
    }`,
    why: '與 RegExp 的區間不同；match 的性質測試',
  },
  {
    name: '句型：量詞上限差一',
    file: 'src/pattern/match.js',
    find: `    if (count < node.max) {
      for (const e of ends(node.node, i)) {
        if (e > i) pushUnique`,
    replace: `    if (count <= node.max) {
      for (const e of ends(node.node, i)) {
        if (e > i) pushUnique`,
    why: 'x{0,1} 比到兩次；match 的性質測試',
  },
  {
    name: '句型：擇一的分支倒過來試',
    file: 'src/pattern/match.js',
    find: '        for (const o of node.options) pushUnique(out, seen, ends(o, i))',
    replace: '        for (const o of [...node.options].reverse()) pushUnique(out, seen, ends(o, i))',
    why: '優先序與 RegExp 不同；match 的性質測試',
  },
  {
    name: '句型：下一次從起點的下一個位置接著找（區間重疊）',
    file: 'src/pattern/match.js',
    find: '      pos = e > s ? e : e + 1',
    replace: '      pos = s + 1',
    why: '與 RegExp 的 g 不同；match 的性質測試',
  },
  {
    name: '句型：不分句',
    file: 'src/pattern/sentences.js',
    find: '      if (isSeparator(ch)) flush(SENTENCE_END.test(ch))',
    replace: '      if (isSeparator(ch)) flush(false)',
    why: '^ $ 與 _* 跨句；sentences 的分句測試、search 的 ^ $ 測試',
  },
  {
    name: '句型：前綴不錨定在最外層（任何位置都算）',
    file: 'src/pattern/morph.js',
    find: '  const prefixOk = req.prefixesAnywhere ? anywhere(req.prefixes, reading.left) : runAt(req.prefixes, reading.left, 0)',
    replace: '  const prefixOk = anywhere(req.prefixes, reading.left)',
    why: 'mi-… 找到 kamikita（ka-mi-kita），v0.6.0 的 imini 雜訊；morph 的 imini 測試、search 的 kamikita 測試',
  },
  {
    name: '句型：後綴錨在內側（從第一個後綴算起）',
    file: 'src/pattern/morph.js',
    find: '    : runAt(req.suffixes, reading.right, reading.right.length - req.suffixes.length)',
    replace: '    : runAt(req.suffixes, reading.right, 0)',
    why: '…-an-ay 找不到 x-i-an-ay、卻找到 x-an-ay-i；morph 的後綴測試',
  },
  {
    name: '句型：列出的前綴不必相連（子序列）',
    file: 'src/pattern/morph.js',
    find: '  const runAt = (want, have, at) => at >= 0 && at + want.length <= have.length && want.every((g, i) => g.forms.has(have[at + i].form))',
    replace: `  const runAt = (want, have, at) => {
    let j = 0
    for (const m of have.slice(Math.max(0, at))) if (j < want.length && want[j].forms.has(m.form)) j++
    return at >= 0 && j === want.length
  }`,
    why: 'pa-ka-… 找到 pa-ma-ka-x；morph 的相連測試',
  },
  {
    name: '句型：… 不優先當詞根（寫出的詞根與 … 一起競爭）',
    file: 'src/pattern/morph.js',
    find: '    const valid = wildRoots.length ? wildRoots : readings',
    replace: '    const valid = readings',
    why: 'saa-i-… 型報 E_AMBIGUOUS_ROOT；morph 的 tau-i-… 測試',
  },
  {
    name: '句型：外側的 … 被當成錨定',
    file: 'src/pattern/morph.js',
    find: '      prefixesAnywhere: rootAt !== 0 && core[0].wildcard,',
    replace: '      prefixesAnywhere: false,',
    why: '…-pa-… 找不到 mupakita；morph 的外側 … 測試、search 的 mupakita 測試',
  },
  {
    name: '句型：先扣音變再求最好的拆法',
    file: 'src/pattern/morph.js',
    find: '  const best = Math.min(floor, ...parses.filter((x) => !x.virtual).map((x) => x.cost))',
    replace: '  const best = Math.min(floor, ...parses.filter((x) => !x.virtual && x.sound <= sound + EPSILON).map((x) => x.cost))',
    why: '精確模式改取比最好的差、但沒有音變的拆法；morph 的「先求最好的再扣音變」測試',
  },
  {
    name: '句型：標準模式取差 0.2 以內的拆法',
    file: 'src/pattern/morph.js',
    find: '  normal: Object.freeze({ spread: 0.1, sound: 0.2 }),',
    replace: '  normal: Object.freeze({ spread: 0.2, sound: 0.2 }),',
    why: '標準多收了差 0.2 的拆法；morph 的 PARSE_SELECTION 測試',
  },
  {
    name: '句型：不限制音變',
    file: 'src/pattern/morph.js',
    find: '  return parses.filter((x) => (x.virtual || x.cost <= best + spread + EPSILON) && x.sound <= sound + EPSILON)',
    replace: '  return parses.filter((x) => x.virtual || x.cost <= best + spread + EPSILON)',
    why: '標準收下音變 0.3 的拆法；morph 的音變上限測試',
  },
  {
    name: '句型：取拆法從最好的拆法算起，不看 BCDP 最好的命中',
    file: 'src/pattern/search.js',
    find: '      const selected = selectParses(all, level, floor)',
    replace: '      const selected = selectParses(all, level)',
    why: '標準模式把 pabak 拆成 pa-pa-rak（最好的命中是同長的 barak）；search 的 pabak 測試',
  },
  {
    name: '句型：拆解表不記 BCDP 最好的命中',
    file: 'src/search/derivations.js',
    find: "  const best = hits.length && (Array.from(hits[0].term).length >= length || hits[0].term.includes(' ')) ? roundCost(hits[0].distance) : null",
    replace: '  const best = null',
    why: '同上，由建置端漏掉；search 的 pabak 測試、拆解表對自動派生圖測試',
  },
  {
    name: '句型：虛擬詞根與詞庫拆法一起求最好的成本（虛擬詞根把詞庫拆法擠掉）',
    file: 'src/pattern/morph.js',
    find: '  const best = Math.min(floor, ...parses.filter((x) => !x.virtual).map((x) => x.cost))',
    replace: '  const best = Math.min(floor, ...parses.map((x) => x.cost))',
    why: 'pinahazaban 型：mausay 的 usa 落選；search 的精確對自動派生圖、虛擬詞根不擠掉詞庫拆法、mausay 測試',
  },
  {
    name: '句型：虛擬詞根的拆法也要在最好的詞庫拆法差 spread 之內',
    file: 'src/pattern/morph.js',
    find: '  return parses.filter((x) => (x.virtual || x.cost <= best + spread + EPSILON) && x.sound <= sound + EPSILON)',
    replace: '  return parses.filter((x) => x.cost <= best + spread + EPSILON && x.sound <= sound + EPSILON)',
    why: '最好的命中不是拆法時，成本較高的虛擬詞根拆法落選（自動派生圖的邊）；morph 的「虛擬詞根的拆法不看與詞庫拆法差多少」測試',
  },
  {
    name: '句型：證據先取虛擬詞根的拆法',
    file: 'src/pattern/search.js',
    find: '      list = [...selected.filter((x) => !x.virtual), ...selected.filter((x) => x.virtual)].map((x) => ({',
    replace: '      list = selected.map((x) => ({',
    why: 'mausay 的 …-ay 說明成虛擬詞根；search 的 mausay 測試',
  },
  {
    name: '句型：詞庫外的詞沒有拆法（例句體例展開的讀法比不到構詞樣式）',
    file: 'src/pattern/search.js',
    find: "      const { all, floor } = id === -1 ? this._unlistedParses(key) : { all: chart.of(id), floor: chart.lexicalBestOf(id) }",
    replace: "      const { all, floor } = id === -1 ? { all: [], floor: Infinity } : { all: chart.of(id), floor: chart.lexicalBestOf(id) }",
    why: 'yaku pa-ka-… 找不到 yaku pa(ka)kita isiw；search 的詞庫外的詞測試、找得到自己測試',
  },
  {
    name: '句型：不加引號的詞不查詞庫外的讀法',
    file: 'src/pattern/search.js',
    find: "      for (const r of this.unlistedIndex?.search(key, { maxDistance: level.maxDistance(n), normalization: 'max', maxNormalized: level.maxNormalized }) ?? []) {",
    replace: '      for (const r of []) {',
    why: 'yaku pakakita 找不到 yaku pa(ka)kita isiw；search 的詞庫外的詞測試',
  },
  {
    name: '句型：詞庫外的詞不算虛擬詞根',
    file: 'src/pattern/search.js',
    find: '      const virtual = a.virtual.map((v) => parsedAnalysis(v.stem, true, roundCost(v.cost), v.steps))',
    replace: '      const virtual = [].map((v) => parsedAnalysis(v.stem, true, roundCost(v.cost), v.steps))',
    why: 'masay 沒有虛擬詞根 asay 的拆法，與把它加進詞庫時的拆解表不同；search 的詞庫外的詞測試',
  },
  {
    name: '句型：證據取這個詞最好的拆法，不是符合條件的那一種',
    file: 'src/pattern/search.js',
    find: '    for (const parse of this._parsesOf(key, fuzziness)) if ((roots === null || roots.has(parse.root)) && satisfies(req, parse.reading)) return parse',
    replace: `    const list = this._parsesOf(key, fuzziness)
    if (list.some((parse) => (roots === null || roots.has(parse.root)) && satisfies(req, parse.reading))) return list[0]`,
    why: '…-pa-… 的 mupakita 說明成 mu- ＋ pakita；search 的證據測試',
  },
  {
    name: '句型：不錨定的提示把原本就找到的詞也算進去',
    file: 'src/pattern/search.js',
    find: '    for (const key of this.corpus.docsOf.keys()) if (!found.has(key) && this._matchParse(key, wider, roots, fuzziness)) count++',
    replace: '    for (const key of this.corpus.docsOf.keys()) if (this._matchParse(key, wider, roots, fuzziness)) count++',
    why: 'W_INNER_AFFIX 的數量不是多找到的詞形數；search 的提示測試',
  },
  {
    name: '句型：拆解表漏掉虛擬詞根',
    file: 'src/search/parses.js',
    find: "      virtual.map((e) => ({ ...e, analysis: { ...e.analysis, notes: [] } })),",
    replace: '      [],',
    why: 'mausay、mupuza 的虛擬詞根不在拆解表；search 的拆解表對自動派生圖測試',
  },
  {
    name: '句型：拆解表收下含空白的詞根',
    file: 'src/search/derivations.js',
    find: "    if (!hit.term.includes(' ')) {\n      for (const steps of",
    replace: "    if (hit.term) {\n      for (const steps of",
    why: 'pakakita 拆成 pa- ＋「ka kita」；search 的單一個詞測試',
  },
  {
    name: '句型：拆解表只收最好的詞根（次佳的拆法不見了）',
    file: 'src/search/derivations.js',
    find: "    if (!hit.term.includes(' ')) {\n      for (const steps of",
    replace: "    if (hit.distance > hits[0].distance + EPSILON) continue\n    if (!hit.term.includes(' ')) {\n      for (const steps of",
    why: 'pakanen 的 pa-kan-en（次佳）不在拆解表；search 的 pakanen 測試、拆解表對一般搜尋的自動拆解測試',
  },
  {
    name: '句型：同位詞素組只取寫法本身',
    file: 'src/pattern/morph.js',
    find: "      return [{ type: side, forms: group, label: labelOf(side, form) }]",
    replace: "      return [{ type: side, forms: new Set([form]), label: labelOf(side, form) }]",
    why: 'mu-… 與 mi-… 結果不同；search 的同位詞素組測試',
  },
  {
    name: '句型：引號沒有關掉歸併',
    file: 'src/pattern/morph.js',
    find: '    if (quoted) return group ? [{ type: side, forms: new Set([form]), label: labelOf(side, form) }] : fail()',
    replace: '    if (quoted) return group ? [{ type: side, forms: group, label: labelOf(side, form) }] : fail()',
    why: '"mu"-… 找到 mikita；search 的引號測試',
  },
  {
    name: '句型：句末的驚嘆號也觸發句型搜尋',
    file: 'src/pattern/detect.js',
    find: String.raw`  { reason: '!', test: /(?:^|[\s(|&])!(?=[\p{L}"“(@_!^])/u },`,
    replace: "  { reason: '!', test: /!/u },",
    why: 'bunang ka lalan! 改用句型搜尋；detect 的一般搜尋清單',
  },
  {
    name: '句型：& ! 的條件被忽略',
    file: 'src/pattern/search.js',
    find: '            if (matchesAnywhere(cond.body, tokens.length, test)) return null',
    replace: '            void matchesAnywhere',
    why: 'yaku & !hapet 仍找到含 hapet 的句子；search 的 & ! 測試',
  },
  {
    name: '句型：可省略的詞也當成必經的詞篩選候選',
    file: 'src/pattern/ast.js',
    find: '      return node.min >= 1 ? requiredAtoms(node.node) : []',
    replace: '      return requiredAtoms(node.node)',
    why: 'minukan isiw? yaku 篩掉沒有 isiw 的句子；search 的候選篩選對照',
  },
  {
    name: '人工拆解：重疊部分當成詞綴',
    file: 'src/search/segmentation.js',
    find: "    if (p === '~') segs.pop() // 重疊部分不是詞綴",
    replace: "    if (p === '~') continue",
    why: 'ki~kita 的 ki 變成前綴；segmentation 的拆解解析與「只有重疊」測試',
  },
  {
    name: '人工拆解：組合寫法拆成第一個詞素組比',
    file: 'src/search/segmentation.js',
    find: '    if (req && groups.length === 1) {',
    replace: '    if (req && groups.length >= 1) {',
    why: 'min- 被當成 m- 比到，不再是規格沒有的詞綴；segmentation 的聯集與檢查清單數量',
  },
  {
    name: '人工拆解：同一個詞的幾筆拆解不取聯集',
    file: 'src/search/segmentation.js',
    find: '    const truth = /** @type {Set<string>} */ (truthOf.get(r.word))',
    replace: '    const truth = new Set(r.affixes.map((a) => a.condition).filter((c) => c !== null))',
    why: 'mineken 的第二筆（min-）把 m-、<in> 算成誤配；segmentation 的聯集測試與句型搜尋對照',
  },
  {
    name: '人工拆解：詞根不在詞庫不檢查',
    file: 'src/search/segmentation.js',
    find: "      rootInLexicon: r.root !== '' && engine.index.dawg.lookup(r.root) !== -1,",
    replace: '      rootInLexicon: true,',
    why: 'pakan 的詞根 pak 不再標出；segmentation 的每筆記錄與檢查清單篩選',
  },
  {
    name: '人工拆解：準確與召回對調',
    file: 'src/search/checklist.js',
    find: '      totals: { tp, fp, fn, precision: tp + fp ? tp / (tp + fp) : null, recall: tp + fn ? tp / (tp + fn) : null },',
    replace: '      totals: { tp, fp, fn, precision: tp + fn ? tp / (tp + fn) : null, recall: tp + fp ? tp / (tp + fp) : null },',
    why: '檢查清單顯示的準確與召回對調；segmentation 的檢查清單數量測試',
  },
  {
    name: '自動同根：查詢本身是別的詞的詞根時連詞庫詞根的同根也不找',
    file: 'src/search/engine.js',
    find: '    for (const m of lemma) {',
    replace: '    for (const m of isLexicalRoot(this.index, self, (id) => graph.hasChildren(id)) ? [] : lemma) {',
    why: 'musamian（musamianan 的詞根）找不到 masamian，反方向找得到；derivations 的對稱測試與 symmetry 的同根對稱',
  },
  {
    name: '虛擬詞根：查詢端的詞庫最好成本取所有命中的最低（含詞根不比查詢短的）',
    file: 'src/search/engine.js',
    find: '    return open ? virtualRoots(key, open, this.index, lexicalEdgeCost(key, lemma)) : []',
    replace: '    return open ? virtualRoots(key, open, this.index, Math.min(Infinity, ...lemma.map((m) => m.distance))) : []',
    why: '同樣長的相近詞把虛擬詞根擋掉，查詢與建置不一致；symmetry 的一致性測試',
  },
  {
    name: '自動同根的排序只看例句最弱的命中方式',
    file: 'src/search/scoring.js',
    find: "export const siblingTier = (h) => (h.matchType === 'sibling' || ",
    replace: "export const siblingTier = (h) => (h.matchType === 'sibling' || false && ",
    why: '一個詞自動同根、另一個詞結尾相符的例句佔上限；derivations 的多詞查詢測試',
  },
  {
    name: '空白可以與字母互換（邊界的價錢讓字母消失）',
    file: 'src/fuzzy/costs.js',
    find: '    if (this.boundaries.has(a) !== this.boundaries.has(b)) return Infinity',
    replace: '    if (this.boundaries.has(a) !== this.boundaries.has(b)) return 0.1',
    why: 'dabran ≈ da ran 只要 0.1（pinahazaban 經 b → 空白找到 daran）；distance 測試',
  },
  {
    name: '拆解表：同分的其他讀法不收',
    file: 'src/search/derivations.js',
    find: '      for (const steps of [hit.steps, ...(hit.ties ?? [])]) parses.push',
    replace: '      for (const steps of [hit.steps]) parses.push',
    why: '<a>…-en 找不到 aidemen（同分時只留前綴 a- 的讀法）；pattern 測試「表面相同的讀法都收」',
  },
  {
    name: '同分的讀法不要求步驟成本相同',
    file: 'src/fuzzy/morph-search.js',
    find: '          if (!seen.has(k) && Math.abs(stepCostOf(s) - stepCost) <= EPSILON) seen.add(k), ties.push(s)',
    replace: '          if (!seen.has(k)) seen.add(k), ties.push(s)',
    why: '多一個步驟、少一些音變的讀法鑽過精確模式的音變上限（morohot）；symmetry 的同分讀法測試',
  },
  {
    name: '詞根音節數的成本沒加進命中的成本',
    file: 'src/fuzzy/morph-search.js',
    find: 'const distance = hasRootCost ? roundCost(r.distance + rootCost(r.term)) : r.distance',
    replace: 'const distance = r.distance',
    why: '名次不受音節數影響；bcdp-reference 的詞根音節數隨機比對（ref-morph 加上詞根成本）',
  },
  {
    name: '相對上限的最佳不算詞根成本（構詞搜尋沒有給 termCost）',
    file: 'src/fuzzy/morph-search.js',
    find: '      ...(hasRootCost ? { termCost: rootCost } : {}),',
    replace: '',
    why: '最佳比 finish 的低，剪掉了「最佳 ＋ lemmaSpread」之內的詞根；bcdp-reference 的詞根音節數隨機比對（較窄的 lemmaSpread）',
  },
  {
    name: '相對上限的最佳不算詞根成本（FuzzyIndex 忽略 termCost）',
    file: 'src/fuzzy/fuzzy-index.js',
    find: 'const total = ch.cutoff.termCost ? roundCost(distance + ch.cutoff.termCost(result.term)) : distance',
    replace: 'const total = distance',
    why: '同上，錯在走訪的一側；bcdp-reference 的詞根音節數隨機比對',
  },
  {
    name: '相對上限的起點（seed）不算詞根成本',
    file: 'src/fuzzy/morph-search.js',
    find: 'const total = hasRootCost ? roundCost(cost + rootCost(term)) : cost',
    replace: 'const total = cost',
    why: '起點比真正的最佳低，剪掉了 lemmaSpread 之內的雙音節詞根（原型的第一版就有這個錯）；bcdp-reference 的固定案例 mabak → boku',
  },
  {
    name: '總成本上限比含詞根成本的總和',
    file: 'src/fuzzy/morph-search.js',
    find: 'if (r.term === query || Array.from(r.term).length < spec.minStem || r.distance > maxDistance + EPSILON) continue',
    replace: 'if (r.term === query || Array.from(r.term).length < spec.minStem || r.distance + rootCost(r.term) > maxDistance + EPSILON) continue',
    why: '靠近上限的正確詞根因為詞根成本消失（研究紀錄 U.27：10 組確定詞對）；bcdp-reference（ref-morph 的上限比不含詞根成本的成本）',
  },
  {
    name: '音節數超過成本表時當作 0',
    file: 'src/fuzzy/morphology.js',
    find: '    return table[Math.min(n, table.length - 1)]',
    replace: '    return table[n] ?? 0',
    why: '「最大的鍵也套用到更多音節」沒有做到；morphology.test 的 rootSyllableCost 測試（aitukuan 五個音節）',
  },
  {
    name: '音變不扣詞根成本（soundOf）',
    file: 'src/search/derivations.js',
    find: 'a.steps.reduce((x, s) => x + s.cost, 0) - rootCost))',
    replace: 'a.steps.reduce((x, s) => x + s.cost, 0)))',
    why: '詞根成本被當成音變，自動同根與精確模式的上限變嚴；parses.test 的詞根成本測試',
  },
  {
    name: '拆法的音變不扣詞根成本（parsedAnalysis）',
    file: 'src/search/parses.js',
    find: 'const sound = Math.max(0, roundCost(cost - steps.reduce((sum, x) => sum + x.cost, 0) - rootCost))',
    replace: 'const sound = Math.max(0, roundCost(cost - steps.reduce((sum, x) => sum + x.cost, 0)))',
    why: '精確模式的音變上限把詞根成本算進去；parses.test 的詞根成本測試',
  },
  {
    name: '自動派生圖的音變不扣詞根成本（建置端的自動同根）',
    file: 'src/search/derivations.js',
    find: 'soundOf(analysis, this.rootCostOf(s.id))',
    replace: 'soundOf(analysis)',
    why: '建置端的上限比查詢端嚴，同根不對稱；parses.test 的「自動派生圖：…音變上限…扣掉詞根成本」',
  },
  {
    name: '查詢端的自動同根不扣詞根成本',
    file: 'src/search/engine.js',
    find: 'soundOf({ cost: m.distance, steps: m.analysis.steps }, m.analysis.rootCost ?? 0)',
    replace: 'soundOf({ cost: m.distance, steps: m.analysis.steps })',
    why: '查詢端的上限比建置端嚴，同根不對稱；symmetry 的「查詢端的自動同根」測試',
  },
  {
    name: '詞根成本不分詞條與其他（一律當詞條）',
    file: 'src/fuzzy/morph-search.js',
    find: 'const rootCost = (term) => syllableCost(term, isEntry(term))',
    replace: 'const rootCost = (term) => syllableCost(term)',
    why: '只出現在例句中的雙音節詞根也是 0；bcdp-reference 的固定案例 makiti 與隨機比對（隨機一半的詞根是詞條）',
  },
  {
    name: '詞條與其他的成本表對調',
    file: 'src/fuzzy/morphology.js',
    find: 'const table = isEntry ? entry : other',
    replace: 'const table = isEntry ? other : entry',
    why: '辭典的詞條反而比較貴；morphology.test 的 entry／other 測試',
  },
  {
    name: '虛擬詞根不加音節成本',
    file: 'src/search/derivations.js',
    find: 'return roundCost(spec.virtualRootLengthCost * Array.from(stem).length + rootCostOf(spec)(stem, false))',
    replace: 'return roundCost(spec.virtualRootLengthCost * Array.from(stem).length)',
    why: '虛擬詞根比詞庫中的非詞條詞根便宜；derivations.test 的虛擬詞根成本測試',
  },
  {
    name: '虛擬詞根的分析成本含音節成本',
    file: 'src/search/derivations.js',
    find: 'cost: roundCost(h.distance - (h.rootCost ?? 0)), steps: h.steps',
    replace: 'cost: h.distance, steps: h.steps',
    why: '音節成本在邊上又在代價裡，算兩次，也被當成音變；derivations.test 的虛擬詞根音節成本測試',
  },
  {
    name: '例句中的詞也算詞條',
    file: 'src/search/derivations.js',
    find: '.some((code) => decodePosting(code).kind !== \'token\')))',
    replace: '.length > 0))',
    why: '只出現在例句中的詞當成詞條，成本 0；derivations.test 的詞條測試',
  },
  {
    name: '自動同根的路徑上限算進詞根成本',
    file: 'src/search/derivations.js',
    find: 'const capped = cost - this.rootCostOf(s.id) - (s.rootCost ?? 0)',
    replace: 'const capped = cost',
    why: '詞根成本讓同根超過路徑上限而消失；parses.test 的「自動派生圖：…路徑上限都扣掉詞根成本」',
  },
  {
    name: '自動派生的路徑上限算進詞根成本（走得到的詞）',
    file: 'src/search/derivations.js',
    find: 'if (this.analyses[c.analysis].cost - this.rootCostOf(x) > maxPath + EPSILON || reach.has(c.word)) continue',
    replace: 'if (this.analyses[c.analysis].cost > maxPath + EPSILON || reach.has(c.word)) continue',
    why: '邊的成本因為詞根成本超過上限時走不到下一層（性質測試 B1 失敗 87 個）；parses.test 的兩層 bak → bakan → bakanan',
  },
  {
    name: '自動派生的路徑上限算進詞根成本（鬆弛）',
    file: 'src/search/derivations.js',
    find: 'const path = at.path + edge - this.rootCostOf(x)',
    replace: 'const path = at.path + edge',
    why: '同上，錯在鬆弛的一步；symmetry 的「查詞根找得到它的衍生詞」',
  },
]
